# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import _SpecialForm, Any

class Int[T]:
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: Int) -> Int: ...
    def __sub__(self, other: Int) -> Int: ...
    def __mul__(self, other: Int) -> Int: ...
    def __floordiv__(self, other: Int) -> Int: ...
    def __mod__(self, other: Int) -> Int: ...
    def __int__(self) -> int: ...

IntVar: _SpecialForm

shaped_array: Any
