# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, Literal, overload

import shape_extensions
from numpy._shapes import binary_ufunc_ir, diag_1d_ir, matmul_2d_ir, reduce_ir
from shape_extensions import SymInt, SymIntTuple, SymIntVar, uses_shape_dsl

from . import linalg as linalg, random as random

type _Shape = SymIntTuple
type _AnyShape = tuple[Any, ...]
type _Axis = int | tuple[int, ...] | None

class generic: ...
class bool_(generic): ...
class float32(generic): ...
class float64(generic): ...
class int32(generic): ...
class int64(generic): ...
class intp(generic): ...

class dtype[Scalar = Any]:
    @overload
    def __new__[ScalarT: generic](cls, dtype: type[ScalarT]) -> dtype[ScalarT]: ...
    @overload
    def __new__(cls, dtype: Any = ...) -> dtype: ...
    def __init__(self, dtype: Any = ...) -> None: ...

@shape_extensions.shaped_array(shape="Shape")
class ndarray[Shape: _Shape = _AnyShape, DType = Any]:
    shape: Shape
    dtype: DType
    @overload
    def __len__[N: SymIntVar](self: ndarray[[N]]) -> SymInt[N]: ...
    @overload
    def __len__[N: SymIntVar, M: SymIntVar](self: ndarray[[N, M]]) -> SymInt[N]: ...
    def __getitem__[
        N: SymIntVar,
        M: SymIntVar,
        I: SymIntVar,
        RowIndexScalar: (int32, int64, intp),
        ColumnIndexScalar: (int32, int64, intp),
    ](
        self: ndarray[[N, M], DType],
        key: tuple[
            ndarray[[I], dtype[RowIndexScalar]],
            ndarray[[I], dtype[ColumnIndexScalar]],
        ],
    ) -> ndarray[[I], DType]: ...
    # Only 2-D transpose is modeled for the NumPy shape-stub MVP.
    @property
    def T[N: SymIntVar, P: SymIntVar](
        self: ndarray[[N, P], DType],
    ) -> ndarray[[P, N], DType]: ...
    @overload
    def __add__(self, other: int | float) -> ndarray[Shape, DType]: ...
    @uses_shape_dsl(binary_ufunc_ir)
    @overload
    def __add__(self, other: ndarray) -> ndarray[_AnyShape, DType]: ...
    @overload
    def __radd__(self, other: int | float) -> ndarray[Shape, DType]: ...
    @uses_shape_dsl(binary_ufunc_ir)
    @overload
    def __radd__(self, other: ndarray) -> ndarray[_AnyShape, DType]: ...
    @uses_shape_dsl(binary_ufunc_ir)
    @overload
    def __sub__(self, other: ndarray) -> ndarray[_AnyShape, DType]: ...
    @overload
    def __sub__(self, other: int | float) -> ndarray[Shape, DType]: ...
    @uses_shape_dsl(binary_ufunc_ir)
    @overload
    def __rsub__(self, other: ndarray) -> ndarray[_AnyShape, DType]: ...
    @overload
    def __rsub__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __truediv__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __rtruediv__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __mul__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __rmul__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __neg__(self) -> ndarray[Shape, DType]: ...
    def __pos__(self) -> ndarray[Shape, DType]: ...
    def __pow__(self, other: int | float) -> ndarray[Shape, DType]: ...
    # TODO: Bridge until operator dunders/bound methods can share the DSL-backed
    # `np.matmul` rule and diagnostics.
    def __matmul__[N: SymIntVar, M: SymIntVar, P: SymIntVar](
        self: ndarray[[N, M], DType],
        other: ndarray[[M, P]],
    ) -> ndarray[[N, P], DType]: ...
    # Narrow method bridge for PCA demos; the free `np.mean` covers general reductions.
    @overload
    def mean[N: SymIntVar, M: SymIntVar](
        self: ndarray[[N, M], DType],
        axis: Literal[0],
        *,
        keepdims: Literal[False] = False,
    ) -> ndarray[[M], DType]: ...
    @overload
    def mean[N: SymIntVar](
        self: ndarray[[N], DType],
    ) -> ndarray[tuple[()], DType]: ...
    @overload
    def sum[N: SymIntVar, M: SymIntVar](
        self: ndarray[[N, M], DType],
        axis: Literal[1],
        *,
        keepdims: Literal[True],
    ) -> ndarray[[N, 1], DType]: ...
    @overload
    def sum[N: SymIntVar, M: SymIntVar, K: SymIntVar](
        self: ndarray[[N, M, K], DType],
        axis: Literal[1],
        *,
        keepdims: Literal[False] = False,
    ) -> ndarray[[N, K], DType]: ...
    def max[N: SymIntVar, M: SymIntVar](
        self: ndarray[[N, M], DType],
        axis: Literal[1],
        *,
        keepdims: Literal[True],
    ) -> ndarray[[N, 1], DType]: ...

def abs[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def exp[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log2[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log10[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def sqrt[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def power[Shape: _Shape](x1: ndarray[Shape], x2: int | float, /) -> ndarray[Shape]: ...
@uses_shape_dsl(binary_ufunc_ir)
def minimum(x1: ndarray, x2: ndarray, /) -> ndarray: ...
@uses_shape_dsl(binary_ufunc_ir)
def maximum(x1: ndarray, x2: ndarray, /) -> ndarray: ...
@uses_shape_dsl(binary_ufunc_ir)
def arctan2(x1: ndarray, x2: ndarray, /) -> ndarray: ...
def sin[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def cos[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def tan[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def arcsin[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def floor[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def ceil[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def round[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def trunc[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def clip[Shape: _Shape](
    a: ndarray[Shape], a_min: int | float, a_max: int | float
) -> ndarray[Shape]: ...
def negative[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def fill_diagonal[N: SymIntVar, DType](
    a: ndarray[[N, N], DType],
    val: Any,
    wrap: bool = False,
) -> None: ...
@uses_shape_dsl(diag_1d_ir)
def diag[DType](
    v: ndarray[_AnyShape, DType], k: int = 0
) -> ndarray[_AnyShape, DType]: ...
def arange[N: SymIntVar](stop: SymInt[N], /) -> ndarray[[N], dtype[intp]]: ...
@overload
def expand_dims[N: SymIntVar, M: SymIntVar, DType](
    a: ndarray[[N, M], DType],
    axis: Literal[0, -3],
) -> ndarray[[1, N, M], DType]: ...
@overload
def expand_dims[N: SymIntVar, M: SymIntVar, DType](
    a: ndarray[[N, M], DType],
    axis: Literal[1, -2],
) -> ndarray[[N, 1, M], DType]: ...
@overload
def expand_dims[N: SymIntVar, M: SymIntVar, DType](
    a: ndarray[[N, M], DType],
    axis: Literal[2, -1],
) -> ndarray[[N, M, 1], DType]: ...
@uses_shape_dsl(reduce_ir)
def sum(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def mean(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def min(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def max(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@overload
def argmin[N: SymIntVar, M: SymIntVar](
    a: ndarray[[N, M]],
    axis: Literal[0, -2],
    *,
    keepdims: Literal[False] = False,
) -> ndarray[[M], dtype[intp]]: ...
@overload
def argmin[N: SymIntVar, M: SymIntVar](
    a: ndarray[[N, M]],
    axis: Literal[1, -1],
    *,
    keepdims: Literal[False] = False,
) -> ndarray[[N], dtype[intp]]: ...
@uses_shape_dsl(matmul_2d_ir)
def matmul(a: ndarray, b: ndarray, /) -> ndarray: ...

# TODO(stroxler): Replace these finite tuple-shape constructor overloads with a
# generic `Shape: tuple[int, ...]` overload once carrier shapes flow through
# downstream shaped-array operations without degrading to unknown.
@overload
def zeros[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def zeros[N: SymIntVar](
    shape: SymInt[N], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def zeros[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def zeros[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: None = ..., order: str = ...
) -> ndarray[[N, M], dtype[float64]]: ...
@overload
def zeros[N: SymIntVar](
    shape: SymInt[N], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def zeros[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def zeros[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: Any, order: str = ...
) -> ndarray[[N, M]]: ...
@overload
def ones[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def ones[N: SymIntVar](
    shape: SymInt[N], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def ones[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def ones[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: None = ..., order: str = ...
) -> ndarray[[N, M], dtype[float64]]: ...
@overload
def ones[N: SymIntVar](
    shape: SymInt[N], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def ones[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def ones[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: Any, order: str = ...
) -> ndarray[[N, M]]: ...
@overload
def full[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def full[N: SymIntVar](
    shape: SymInt[N], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[[N]]: ...
@overload
def full[N: SymIntVar](
    shape: tuple[SymInt[N]], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[[N]]: ...
@overload
def full[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]],
    fill_value: Any,
    dtype: Any = ...,
    order: str = ...,
) -> ndarray[[N, M]]: ...
@overload
def empty[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar, ScalarT: generic](
    shape: SymInt[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar, M: SymIntVar, ScalarT: generic](
    shape: tuple[SymInt[N], SymInt[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N, M], dtype[ScalarT]]: ...
@overload
def empty[N: SymIntVar](
    shape: SymInt[N], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def empty[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: None = ..., order: str = ...
) -> ndarray[[N], dtype[float64]]: ...
@overload
def empty[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: None = ..., order: str = ...
) -> ndarray[[N, M], dtype[float64]]: ...
@overload
def empty[N: SymIntVar](
    shape: SymInt[N], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def empty[N: SymIntVar](
    shape: tuple[SymInt[N]], dtype: Any, order: str = ...
) -> ndarray[[N]]: ...
@overload
def empty[N: SymIntVar, M: SymIntVar](
    shape: tuple[SymInt[N], SymInt[M]], dtype: Any, order: str = ...
) -> ndarray[[N, M]]: ...
@overload
def eye[N: SymIntVar, ScalarT: generic](
    N: SymInt[N], M: None = ..., k: int = ..., *, dtype: type[ScalarT], order: str = ...
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def eye[N: SymIntVar, ScalarT: generic](
    N: SymInt[N], M: None, k: int, dtype: type[ScalarT], order: str = ...
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def eye[N: SymIntVar, ScalarT: generic](
    N: SymInt[N],
    M: None = ...,
    k: int = ...,
    *,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def eye[N: SymIntVar, ScalarT: generic](
    N: SymInt[N], M: None, k: int, dtype: dtype[ScalarT], order: str = ...
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def eye[N: SymIntVar](
    N: SymInt[N], M: None = ..., k: int = ..., dtype: None = ..., order: str = ...
) -> ndarray[[N, N], dtype[float64]]: ...
@overload
def eye[N: SymIntVar](
    N: SymInt[N], M: None = ..., k: int = ..., dtype: Any = ..., order: str = ...
) -> ndarray[[N, N]]: ...
@overload
def identity[N: SymIntVar, ScalarT: generic](
    n: SymInt[N], dtype: type[ScalarT], *, like: Any = ...
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def identity[N: SymIntVar, ScalarT: generic](
    n: SymInt[N], dtype: dtype[ScalarT], *, like: Any = ...
) -> ndarray[[N, N], dtype[ScalarT]]: ...
@overload
def identity[N: SymIntVar](
    n: SymInt[N], dtype: None = ..., *, like: Any = ...
) -> ndarray[[N, N], dtype[float64]]: ...
@overload
def identity[N: SymIntVar](
    n: SymInt[N], dtype: Any, *, like: Any = ...
) -> ndarray[[N, N]]: ...
