name: build_extension
on:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build_extension:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
          - os: ubuntu-latest
            platform: alpine
            arch: x64
          - os: ubuntu-latest
            platform: alpine
            arch: arm64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Read rust-toolchain file
        id: rust-toolchain
        run: echo "toolchain=$(cat pyre2/rust-toolchain)" >> $GITHUB_STATE
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.toolchain }}
      - name: build pyrefly binary
        run: cargo build --release --all-features --target-dir lsp/bin --manifest-path pyre2/Cargo.toml
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: lsp/
      - shell: pwsh
        run: echo "platform=${{ matrix.platform }}-${{ matrix.arch }}" >> $GITHUB_STATE
      - run: npx vsce package --target ${{ env.platform }}
        working-directory: lsp/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.platform }}
          path: "lsp/*.vsix"
