# name: build_extension
# on:
#   workflow_dispatch:

# jobs:
#     build:
#         uses: ./.github/workflows/build_extension.yml
#     publish:
#         runs-on: ubuntu-latest
#         needs: build
#         if: success() && startsWith( github.ref, 'refs/tags/')
#         steps:
#             - uses: actions/download-artifact@v2
#             - run: npx vsce publish --packagePath $(find . -iname *.vsix)
#             env:
#                 VSCE_PAT: ${{ secrets.VSCE_PAT }}