name: deploy_extension
on:
  workflow_dispatch:
  push:
    paths:
      - pyre2/version.bzl
    branches: [ main, kinto/test-vsce-publish ]

jobs:
    build:
        uses: ./.github/workflows/build_extension.yml

    publish:
        runs-on: ubuntu-latest
        needs: build
        if: success() && startsWith( github.ref, 'refs/tags/')
        steps:
            - name: Get version
              run: echo "PYREFLY_VERSION=$(sed -n -e 's/^VERSION = "\(.*\)"/\1/p' pyre2/version.bzl)" >> $GITHUB_ENV
            - name: upload
              uses: actions/download-artifact@v4
            - name: publish
              run: npx vsce publish ${{ env.PYREFLY_VERSION }} --packagePath $(find . -iname *.vsix)
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}

# TODO: deploy to https://open-vsx.org/ too by adding it here https://github.com/EclipseFdn/publish-extensions/blob/master/extensions.json
