name: deploy_extension
on:
  workflow_dispatch:
  push:
    paths:
      - pyre2/version.bzl
    branches: [ main ]

jobs:
    build:
        uses: ./.github/workflows/build_extension.yml

    publish:
        runs-on: ubuntu-latest
        needs: build
        if: success()
        steps:
            - name: Checkout repo (to see version.bzl in nex step)
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Get all history for all branches and tags
            - name: Get version
              run: echo "PYREFLY_VERSION=$(sed -n -e 's/^VERSION = "\(.*\)"/\1/p' pyre2/version.bzl)" >> $GITHUB_ENV
            - name: upload
              uses: actions/download-artifact@v4
            - name: publish
              run: npx vsce publish ${{ env.PYREFLY_VERSION }} --packagePath $(find . -iname *.vsix)
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}
